# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  key:
    files:
      - poetry.lock
      - .gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .venv/
    - .cache/pip

stages:
  - test
  - build

dev_tests:
  stage: test
  scripts:
    - python --version



dev_build:
  stage: build
  scripts:
    - python --version

#before_script:
#  - python --version
#  - pip install poetry
#  - poetry config virtualenvs.in-project true
#  - poetry install --no-root
#
#pytest:
#  script:
#    - poetry run dvc pull
#    - poetry run dvc repro
#    - poetry run pytest --disable-warnings


#type_test:
#  script:
#    - pip install mypy
#    - mypy --ignore-missing-imports clean_data.py
#

#lint_test:
#  script:
#    - flake8 src/data/clean_data.py